---
title: "Weekly Guide 3"
linktitle: "Week 3"
menu:
  content:
    parent: Weekly Guides
    weight: 3
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we'll finish a few slides from Module 0 (namely, our Medicare Advantage summaries), and we'll begin our first module of the semester -- Pricing and Selection on Observables. This module will introduce us to causal inference, work through the basics of "selection on observables" as a research design, and implement this design to assess whether hospital profit status affects prices.

But first things first! This week, we'll talk about the confusing mess that is hospital prices and the data we'll use to measure them.

### Objectives

- Understand the nature of hospital pricing
- Compare and contrast different measures of hospital "prices" used in popular media

### Activities 

- Clone [Hospital Cost Report Information System (HCRIS)](https://github.com/imccart-test/hcris) repository and begin working with data. See also a similar repository [here](https://github.com/asacarny/hospital-cost-reports) from [Adam Sacarny](http://sacarny.com/)
- Second [weekly check-in](/assignment/weekly-check-in.html) due on Friday.
- [Homework 1](/assignment/homework1.html) due ~~on Friday~~ next week.

### Readings and Other Resources
- For background on hospital prices, see @cooper2019. Link to paper [here](https://academic.oup.com/qje/article/134/1/51/5090426).