---
title: "Weekly Guide 5"
linktitle: "Week 5"
menu:
  content:
    parent: Weekly Guides
    weight: 5
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we start our first attempt to estimate a causal treatment effect. We'll do so with a few approaches, all of which rely on the combination of a "selection on observables" or "conditional independence" assumption, along with a "common support" assumption.


### Objectives
- Understand and explain the differences between matching and re-weighting
- Explain the implicit weighting in OLS regression and how to avoid such weighting
- Calculate an ATE or ATT using regression, matching, and weighting

### Activities 
- Continue working with the [Hospital Cost Report Information System (HCRIS)](https://github.com/imccart/HCRIS) repository. Note the revised repository link on Canvas that has the corrected filepaths for our AWS virtual computer.
- [Weekly check-in](/assignment/weekly-check-in.html) due on Friday.
- Estimate treatment effects with simulated data, using matching, regression, and re-weighting

### Readings and Other Resources
  - Chapter 5 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
  - Chapter 14 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
  - Chapter 3 of [@angrist2009]
