---
title: "Weekly Guide 6"
linktitle: "Week 6"
menu:
  content:
    parent: Weekly Guides
    weight: 6
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we continue our work with matching, reweighting, and regression, but we'll do so with real life data on hospital prices.


### Objectives
- Understand HCRIS data and explain hospital pricing
- Calculate an ATE or ATT using regression, matching, and weighting using real-world pricing data

### Activities 
- Continue working with the [Hospital Cost Report Information System (HCRIS)](https://github.com/imccart/HCRIS) repository. Note the revised repository link on Canvas that has the corrected filepaths for our AWS virtual computer.
- [Weekly check-in](/assignment/weekly-check-in.html) due on Friday.
- Estimate the effect of hospital penalties on hospital pricing

### Readings and Other Resources
  - Chapter 5 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
  - Chapter 14 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
  - Chapter 3 of [@angrist2009]
