---
title: "Weekly Guide 7"
linktitle: "Week 7"
menu:
  content:
    parent: Weekly Guides
    weight: 7
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we'll begin our discussion of smoking and tax policy, focusing on the inherent endogeneity problem when estimating demand with observational data. We'll introduce the idea of instrumental variables as a way to estimate causal effects when confronted with selection on unobservables.


### Objectives
- Understand cigarette data from the CDC Tax Burden on Tobacco
- Derive the instrumental variables estimate
- Define and explain the instrumental variable estimate as a ratio of a "reduced-form" to a "first-stage" estimate


### Activities 
- Work with the [CDC Tax Burden on Tobacco](https://github.com/imccart/CDC-Tobacco) data
- [Weekly check-in](/assignment/weekly-check-in.html) due on Friday

### Readings and Other Resources
- Chapter 7 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
- Chapter 19 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
- Chapter 4 of [@angrist2009]
