---
title: "Weekly Guide 4"
linktitle: "Week 4"
menu:
  content:
    parent: Weekly Guides
    weight: 4
type: docs
bibliography: "../../static/bib/BibTeX_Library.bib"
csl: "../../static/bib/chicago-syllabus-no-bib.csl"
output:
  blogdown::html_page:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

This week, we'll lay the foundation for all of the methods in this class...the potential outcomes framework. We'll discuss what this means and what we'll seek to estimate going forward.


### Objectives

- Explain potential outcomes
- Derive and explain the average treatment effect 
- Explain the differences between an average treatment effect and the average treatment effect on the treated

### Activities 

- Continue working with the [Hospital Cost Report Information System (HCRIS)](https://github.com/imccart/HCRIS) repository. Note the revised repository link on Canvas that has the corrected filepaths for our AWS virtual computer.
- Third [weekly check-in](/assignment/weekly-check-in.html) due on Friday.
- [Homework 1](/assignment/homework1.html) due on Tuesday, 2/1

### Readings and Other Resources
  - Chapter 4 of [Causal Inference: The Mixtape](https://mixtape.scunning.com/)
  - Chapter 10 of [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/)
    - Chapter 2 of [@angrist2009]
