---
title: "Calculus Practice Problems"
linktitle: "Practice problems"
output:
  blogdown::html_page:
    toc: false
menu:
  resource:
    parent: Math Review
    weight: 2
type: docs
---

Below are just some review questions. If you can answer all of these without much trouble, then you should be in good shape in terms of the math requirements for the class.

## Basic derivatives

Find the derivative of the following functions

### Questions

1. $f(x)=3x^{9}$
2. $f(x)=5x^{-2}$
3. $f(x)=5x + 5x^{2}$
4. $f(x)=(\frac{1}{2}x - 4x^{2})^{2}$

### Answers

1. $f'(x) = 27x^{8}$
2. $f'(x) = -10x^{-3}$
3. $f'(x) = 5 + 10x$
4. $f'(x) = 2 ( \frac{1}{2}x - 4x^{2})(\frac{1}{2} - 8x)$


## Demand, profits, and production

### Questions

1. If inverse demand is given by , $P=80-Q$, what is marginal revenue?
2. If a firm's profit function is $\pi = (80-Q)Q - 10Q$, what quantity will maximize the firm's profit? What is the price at this level of $Q$ (hint: inverse demand is the same as in part 1)?
3. The production function is of the Cobb-Douglas form, $Q=AL^{\alpha} K^{1-\alpha}$, where $A$ and $\alpha$ are constants. What are the marginal products of labor ($L$) and capital ($K$)?

### Answers

1. Note that total revenue is $(80-Q)Q$, so marginal revenue is $80-2Q$.
2. To find the optimal $Q$, we need to differentiate, set equal to 0, then solve for $Q$. In this case, $\pi'(Q) = 80 - 2Q - 10$, which equals 0 for $Q=35$. Price at this quantity is $P=80-Q=45$.
3. The marginal product of labor or capital is just the partial derivative of each of those terms. So, $$MP_{L} = \frac{\partial Q}{\partial L} = \alpha A L^{\alpha-1} K^{1-\alpha} = \alpha A \left(\frac{K}{L}\right)^{1-\alpha}$$ and $$MP_{K} = \frac{\partial Q}{\partial K} = (1-\alpha) A L^{\alpha} K^{-\alpha} = (1-\alpha) A \left( \frac{L}{K} \right)^{\alpha}.$$