---
title: "Worksheet 8: Pricing in a Two-price Market"
linktitle: "Two-price market"
output:
  blogdown::html_page:
    toc: false
menu:
  resource:
    parent: Worksheets
    weight: 8
type: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel)

```

Consider the firm's inverse demand curve in the private insurance market, $d=16-q$, and costs, $c(q)=5+q^{2}$. Assume that there exists a public insurer that pays a fixed price of $\bar{p}=10$.<br>

### Question 1
**How many private patients will the provider serve?**


The practice will serve private insurance patients until the marginal revenue from those patients falls below the marginal revenue of a public patient. In this case, the marginal revenue of a public patient is $\bar{p}=10$. The Marginal revenue of a private practice is $16-2q$. These are equal at $q=3$. So the practice will see 3 private insurance patients.

Note, we should check first that the practice will see **any** public patients. The way to do this is to make sure that the marginal revenue from a public patient is above the marginal revenue of $MR=MC$ in the private market. In this case, $MR=MC$ at $q=4$ and $MR=8$. This is below $\bar{p}=10$, so the practice will servce some portion of the public market whenever $\bar{p}>8$. 


### Question 2
**How many public patients?**


The practice will see patients to the point where $MR=\bar{p}=MC$, which holds for $2q=10$, or $q=5$. Combined with our answer in part 1, the practice will see 3 private insurance patients and 2 public insurance patients.


### Question 3
**What if $\bar{p}$ drops to <span>&#36;</span>9.**


In this case, the practice will again see total patients to the point where $MC=\bar{p}$. This holds for $2q=9$, or $q=4.5$. The practice will switch to the public market at $MR=\bar{p}$. This holds for $16-2q=9$, or $q=3.5$. So the drop in the fixed payment rate will lead to an increase in the number of private insurance patients seen (from 3 to 3.5), and a decrease in the number of public patients seen (from 2 to 1). The total number of patients seen in this case also decreases (from 5 to 4.5).