---
title: "Worksheet 6: Physician agency and capitated payments"
linktitle: "Agency with capitation"
output:
  blogdown::html_page:
    toc: false
menu:
  resource:
    parent: Worksheets
    weight: 6
type: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel)

```

Assume that the patient's net benefit function is, $NB(x) = B(x) - p_{d}x$. Further assume that $B(x)=16x-2x^{2}$ and that the patient is fully insured such that $p_{d}=0$ (i.e., the insurer pays the full price of care, and the patient pays nothing). Finally, assume that the physician's number of patients in their practice is governed by, $n(NB)=NB$. The physician receives a fixed payment, $R$, per patient, along with a margin of $p_{s}-c$ for each unit of care, $x$. The same amount of care $x$ is provided to each patient.

### Question 1:
**What is the patient's optimal amount of care?**

If they could, the patient would choose $x$ to maximize their net benefit, $B(x) - p_{d}x = 16x-2x^{2}$. This net benefit is optimized at $x=4$.


### Question 2:
**Write out the physician's profit function.**

The physician's profit is simply their number of patients times the revenue per patient, $\pi = n(NB) \left[R + (p_{s}-c) \right]$. Given the functional forms provided in this question, we can rewrite this as, $\pi = \left(16x - 2x^{2}\right) \left(R + (p_{s}-c)x\right)$.


### Question 3:
**Find the physician's optimal amount of care if $R=0$ and $p_{s}-c=1$**

To find the physician's optimum, we must first take the derivative of the profit function and set this equal to 0, $\frac{\mathrm{d}\pi}{\mathrm{d}x} = (16 - 4x)(R+ (p_{s}-c)x) + (p_{s}-c)(16x-2x^{2})=0$.

Setting $R=0$ and $p_{s}-c=1$, this reduces to $(16-4x)x + 16x - 2x^{2} = 16x-4x^{2} + 16x - 2x^{2} = 32x-6x^{2}=0$. Solving for $x$ yields $x=5.33$. This is larger than the patient's optimal, $x=4$, which should be expected since there is a positive FFS payment in this setup and no capitated payment.

### Question 4:
**Find the physician's optimal amount of care if $R=1$ and $p_{s}-c=1$.**

Plugging these values into the same first order condition, we get $(16-4x)(1+x) + 16x - 2x^{2} = 6x^{2} - 28x - 16=0$. We can solve this with the quadratic equation, in which case $x = \frac{28 \pm \sqrt(1168)}{12} \approx (-0.515, 5.181)$. Since we can't provide negative care, we'll take the positive root so that $x \approx 5.181$. While these numbers are small, the important part is that we've introduced a capitated payment $R=1$ and managed to bring "overtreatment" down from 1.333 to 1.181. In other words, the inclusion of the capitated payment brought us closer to the patient's optimal amount of care.

### Question 5:
**Find the physician's optimal if $R=1$ and $p_{s}-c=0$.**

Again substituting these values into he first order condition, we get $(16-4x) = 0$, or $x=4$. So now the physician and patient optimal are the same value. Note that this is not a general solution...it only arises due to the linear patient function, $n(NB) = a*NB$. For nonlinear functions, we won't generally be able to easily obtain the same optimal values from the physician and patient's perspective. Instead, $R>0$ will yield some amount of undertreatment as we saw in the general case in class.
