---
title: "Worksheet 9: Nash Bargaining"
linktitle: "Nash bargaining"
output:
  blogdown::html_page:
    toc: false
menu:
  resource:
    parent: Worksheets
    weight: 9
type: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel)

```

Assume that two agents are negotiating over how best to divide their quantity of good x, which is normalized to 1. If the players reach an agreement, player 1 receives utility $u_{1} = x$, and player 2 receives utility $u_{2} = (1-x)$. If the players do not reach an agreement, player 1 receives a payoff of $t1 = 0$, and
player 2 receives payoff $t_{2} = a > 0$.<br>


### Question 1
**Find the Nash bargaining solution to this game.**


The Nash bargaining solution is to maximize $x(1-x-a)$ (i.e., the product of each person's payoff under agreement less their payoff under disagreement). We can find the solution by differentiating with respect to $x$ and setting equal to 0, which yields $1-2x - a = 0$, or $x=\frac{1}{2}(1-a)$.


### Question 2
**Explain how this solution varies with $a$.**


As $a$ increases, $x$ decreases. Intuitively, this means that as player 2's outside option improves, less of the total amount $x$ goes to player 1. In other words, if player 2 has the least to lose in the negotiation, then player 2 will extract a larger share of the joint surplus.
